name = "TightBindingToolkit"
uuid = "2233325a-6eb3-486f-aff0-670e0939fa7e"
authors = ["Anjishnu Bose", "Sreekar Voleti"]
version = "1.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Tullio = "^0.2"
MappedArrays = "^0.4"
TensorCast = "^0.3"
julia = "^1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
