name = "TightBindingToolkit"
uuid = "2233325a-6eb3-486f-aff0-670e0939fa7e"
authors = ["Anjishnu Bose", "Sreekar Voleti"]
version = "1.2.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
MappedArrays    = "^0.4"
TensorCast      = "^0.4"
Tullio          = "^0.3"
Plots           = "^1.38"
LaTeXStrings    = "1.3"
PyPlot          = "2.11"  
Statistics      = "^1.8, ^1.9"
julia           = "^1.8, ^1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
